name: 'Lokalise trigger PR  '
description: 'Triggers build on Lokalise that creates a PR '
inputs:
  API_KEY:  # Lokalise API key
    description: 'Who to greet'
    required: true
  PROJECT_KEY: #Lokalise Projekt key 
outputs:
  result: # id of output
    description: 'display wether it when good or not'
runs:
  using: 'node20'
  main: 'index.js'